// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYSQJWuVKFKsUUf9I__GIOIITXNdDznVo',
    appId: '1:897098766352:web:55ae7d780989bd432c9295',
    messagingSenderId: '897098766352',
    projectId: 'dream-125a5',
    authDomain: 'dream-125a5.firebaseapp.com',
    databaseURL: 'https://dream-125a5-default-rtdb.firebaseio.com',
    storageBucket: 'dream-125a5.firebasestorage.app',
    measurementId: 'G-9LR5Z45YMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbZoDcEpigZ9ugazuTJ0rF_6LRgqTIycg',
    appId: '1:897098766352:android:e7fcd76547927b972c9295',
    messagingSenderId: '897098766352',
    projectId: 'dream-125a5',
    databaseURL: 'https://dream-125a5-default-rtdb.firebaseio.com',
    storageBucket: 'dream-125a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeRZhbLL4Cdlz_p84PEiRaUbXuQximL1k',
    appId: '1:897098766352:ios:a5047f2d1f0907792c9295',
    messagingSenderId: '897098766352',
    projectId: 'dream-125a5',
    databaseURL: 'https://dream-125a5-default-rtdb.firebaseio.com',
    storageBucket: 'dream-125a5.firebasestorage.app',
    iosBundleId: 'com.example.device',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeRZhbLL4Cdlz_p84PEiRaUbXuQximL1k',
    appId: '1:897098766352:ios:a5047f2d1f0907792c9295',
    messagingSenderId: '897098766352',
    projectId: 'dream-125a5',
    databaseURL: 'https://dream-125a5-default-rtdb.firebaseio.com',
    storageBucket: 'dream-125a5.firebasestorage.app',
    iosBundleId: 'com.example.device',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYSQJWuVKFKsUUf9I__GIOIITXNdDznVo',
    appId: '1:897098766352:web:528c691ebc6a7f592c9295',
    messagingSenderId: '897098766352',
    projectId: 'dream-125a5',
    authDomain: 'dream-125a5.firebaseapp.com',
    databaseURL: 'https://dream-125a5-default-rtdb.firebaseio.com',
    storageBucket: 'dream-125a5.firebasestorage.app',
    measurementId: 'G-255CVXDW7Y',
  );

}